### ISSUE TITLE
More analysize code

### ISSUE THREAD

**Issue by asinmhk** [jiatiansun/Eventfulness#4]
Hi. Thank you for sharing the interesting project.
Since the code only predicts the raw Event Descriptors currently. 
Are you planning to share more analysize code or have some advises about how to deal with the Descriptors to achieve the mentioned applications in paper, (e.g. to find the temporal peak adaptively, since the predicted data seems lots of noises in some cases.)

**Comment by jiatiansun** [comment]
Hi, we are developing a new visualizer for the event descriptors at the moment and this process has been delayed due to the physical condition of one of our authors. Unfortunately, the other analysis tools also cannot be published at the moment since they use processing code privately developed by [Abe Davis](https://abedavis.com/). 

I recommend to contact [Longxiulin Deng](ld469@cornell.edu) if you would like to get access to the visualizer, and [Abe Davis](abedavis@cornell.edu) for the analysis code. I have limited knowledge about when they are ready to publish their end of the code, but I think they would be willing to share if you ask via email.

If you would like to implement the adaptive eventfulness generation process on your own: the adaptive eventfulness is essentially a linear combination of the event descriptors. To determine the weight of this linear combination, we show users the video alongside the zero-meaned eventfulness signal. By letting them navigate around peaks and choose the peak frames that they consider as "salient/important", we would single out the event descriptors of those frames and treat their average as the weight to generate the adaptive eventfulness. The users can also uniformly scale this weight up and down to further increase or decrease the impact of their selected example frames and generally this would help decrease the "noise" a lot (since without user inputs, the peaks of the eventfulness signal are a super set of all potential salient movements and may appear noisy without any tuning).

**Comment by asinmhk** [comment]
I'll try your advise, thanks for your quick and detailed reply!
